apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pipeline-service
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: pipeline-service
